=== steviemul/vsc-osf/json/pageSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "title",
    "address",
    "shortName",
    "layout"
  ],
  "properties": {
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The Title Schema",  
      "default": "",
      "examples": [
        "Homepage"
      ],
      "pattern": "^(.*)$"
    },
    "address": {
      "$id": "#/properties/address",
      "type": "string",
      "title": "The Address Schema",
      "default": "",
      "examples": [
        "/home"
      ],
      "pattern": "^(.*)$"
    },
    "shortName": {
      "$id": "#/properties/shortName",
      "type": "string",
      "title": "The Shortname Schema",
      "default": "",
      "examples": [
        "home"
      ],
      "pattern": "^(.*)$"
    },
    "secure": {
      "$id": "#/properties/secure",
      "type": "boolean",
      "title": "The Secure Schema",
      "default": false
    },
    "secured": {
      "$id": "#/properties/secured",
      "type": "boolean",
      "title": "The Secured Schema",
      "default": false
    },
    "defaultPage": {
      "$id": "#/properties/defaultPage",
      "type": "boolean",
      "title": "The defaultPage Schema",
      "default": false
    },
    "supportedDevices": {
      "$id": "#/properties/supportedDevices",
      "type": "array",
      "title": "The supportedDevice Schema",
      "items": {
        "$id": "#/properties/supportedDevices/items/properties/supportedDevices/items",
        "type": "string",
        "title": "The Items Schema",
        "enum": ["mobile", "desktop"],
        "default": "",
        "examples": [
          "mobile"
        ]
      }
    },
    "layout": {
      "$id": "#/properties/layout",
      "type": "array",
      "title": "The Layout Schema",
      "items": {
        "$id": "#/properties/layout/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "type",
          "width"
        ],
        "properties": {
          "type": {
            "$id": "#/properties/layout/items/properties/type",
            "type": "string",
            "title": "The Type Schema",
            "default": "",
            "enum": ["header", "main", "footer"],
            "examples": [
              "header"
            ],
            "pattern": "^(.*)$"
          },
          "structure": {
            "$id": "#/properties/regions/items/properties/structure",
            "type": "string",
            "enum": [
              "stack",
              "slot"
            ],
            "title": "The Structure Schema"
          },
          "regions": {
            "$ref": "#/properties/layout"
          },
          "width": {
            "$id": "#/properties/layout/items/properties/width",
            "type": "integer",
            "title": "The Width Schema",
            "default": 12,
            "minimum": 1,
            "maximum": 12
          },
          "components": {
            "$id": "#/properties/layout/items/properties/components",
            "type": "array",
            "title": "The Components Schema",
            "items": {
              "$id": "#/properties/layout/items/properties/components/items",
              "type": "string",
              "title": "The Items Schema",
              "default": "",
              "examples": [
                "MenuMobile"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== steviemul/vsc-osf/json/pageDefinition.json
{
  "title": "title",
  "address": "address",
  "shortName": "shortName",
  "secure": false,
  "layout": [
    {
      "type": "header",
      "width": 12,
      "components": []
    },
    {
      "type": "main",
      "width": 12,
      "components": []
    },
    {
      "type": "footer",
      "width": 12,
      "components": []
    }
  ]
}
